Added ADA changes to directory and Loop
uchicago-library/library_website pull request #489
Opened 2021-03-30 17:50 UTC by kzadrozny

Closes #484 

**Not resolved**
- Mapping issue with CGIMail to `id` is not resolved despite recommended changes (Issue for @bbusenius to review)
- Not able to change Loop text from px to rem right now. Attached to `body` styling from Bootstrap CSS. Will effect entire site and needs more thought.

**Changes in this request**
- Added screen-reader only h3 of staff name outside of divs
- Created h4 labels for About {{ staff name }} and Contact {{ staff name }}
- Made sidebar widgets with icons be entirely wrapped in link tag
- Resolved meta tag ADA issues on Loop templates
- Added links to 404 page (being [served on production](https://www.lib.uchicago.edu/collex/exhibits/adaptations-augie-march-novel-saul-bellow-play-david-auburn-production-directed-charles-newell-exhibition-special-collections-court-theatre/) with reference to links without linked text)
- Expanded `:empty` pseudo class to hid more empty tags from the DOM
- Bumped color contrast on links and Loop items
- Added alt text to Loop logo in footer

2021-03-30 20:47 UTC, kzadrozny commented
Removed CGIMail issue - will move to its own ticket.

2021-03-30 21:48 UTC, bufordrat requested changes
Looks great on my machine and on `nest` generally.  Only thing to work on, which you noted, is what's going on with the alignment of the chat etc. buttons in the right sidebar.

https://liblet.lib.uchicago.edu/about/directory/?view=staff

2021-03-30 21:48 UTC, bufordrat commented on base/templates/base/intranet_base.html
> +  <title>
Nice!

2021-03-31 21:02 UTC, bufordrat approved these changes
Looks great to me!  You can check for yourself here:
https://liblet.lib.uchicago.edu/about/directory/?view=staff

2021-04-01 14:43 UTC, merged