592 create redirect pages within loop
uchicago-library/library_website pull request #606
Opened 2022-09-08 18:23 UTC by bluairis

Fixes #592

Creates a redirect page type for loop pages that generates sidebar links.

# Testing instructions for creating a sidebar link:
1. Navigate to Loop > Groups in the wagtail admin interface
2. Create a child page of one of the pages in Groups
3. Select Loop Redirect Page from the menu of options
4. Enter the link text under title and the URL under redirect URL
5. Populate the rest of the required fields in the content tab
6. Navigate to the promote tab and check the "Show in menus" checkbox under "for site menus"
7. Publish the page

2022-09-12 15:11 UTC, bbusenius requested changes
This looks good. Many of the changes I requested are _very_ minor coding style complaints that show up in my editor. These should be showing up in your editor too. If they aren't showing up there, we might need to do some setup with whatever editor you're using. I can help you with that later but if you just want to manually make the changes now, that's fine.

I know you're aware of this and have been waiting for the new Vagrant environment but just as a reminder, you will need to add the following to this pull request:
1. Migrations
2. Fixtures

To help you with that, I will merge master into this branch. Then you should be able to spin it up in the dev environment.

2022-09-12 15:11 UTC, bbusenius commented on redirects/models.py
> +
Extra blank line should be here.

2022-09-12 15:11 UTC, bbusenius commented on redirects/models.py
> +        Override the serve method to create a redirect.
Delete space at end of line.

2022-09-12 15:11 UTC, bbusenius commented on redirects/models.py
> +        default = "https://loop.lib.uchicago.edu/")
Remove spaces around `=`.

2022-09-12 15:20 UTC, bufordrat commented
Doh!  How did I forget about the fixtures?  Thanks, Brad.  Will help Irina w/ that next time she's in.

2022-09-13 16:54 UTC, bluairis commented on redirects/models.py
When I isort it re-arranges the imports to:
(where `MultiFieldPanel, PageChooserPanel)` is indented)

`from base.models import BasePage, LinkFields, PublicBasePage`
`from django.db import models`
`from django.shortcuts import redirect`
`from wagtail.admin.edit_handlers import (FieldPanel, FieldRowPanel,`
`MultiFieldPanel, PageChooserPanel)`

`from wagtail.core.models import Page`
`from wagtail.documents.edit_handlers import DocumentChooserPanel`
`from wagtail.search import index'

2022-09-13 18:24 UTC, bbusenius approved these changes
Looks good! Thank you!

2022-09-15 15:56 UTC, bufordrat approved these changes
Yup, looks good; ready to go now that we have the fixtures and migrations.

2022-09-16 19:59 UTC, merged