728 mail aliases needs a new test suite
uchicago-library/library_website pull request #746
Opened 2024-04-05 21:06 UTC by bluairis

Fixes #728 

**Changes in this request**

- I added a few tests for the mail aliases page (I did not test each_list because it needs to be fixed pretty soon)
- I made one change to the filter function because the test made me realize that it was removing aliases like "MAILER-DAEMON" from "m" filter value because it was only looking for lowercase first values
- Tests are passing.

2024-04-08 21:19 UTC, bbusenius requested changes
These tests are a good start. I have a couple of suggestions:

1. It would be nice if the names of the test functions conveyed more information about what you're testing about the functions. The Django convention is to use long descriptive function names in tests, rather than docstrings, however, there's nothing wrong with adding a docstring if this isn't possible or if you want to be more descriptive. [Part 5 of the Django tutorial](https://docs.djangoproject.com/en/5.0/intro/tutorial05/) has good information about this.
2. It would be really good to have a test that covers the case for when the MAIL_ALIASES_PATH file isn't found.

2024-04-08 21:19 UTC, bbusenius commented on intranethome/tests.py
> +        self.assertEqual(filter_by_value(aliaslist, ""), aliaslist)
It's good to see you testing for the empty string case.

2024-04-11 16:37 UTC, bufordrat requested changes
Looks great, tests pass on my machine.  I don't have any suggestions other than that I agree with the suggestion to have the site for the case where there is no file at `MAIL_ALIASES_PATH`, and then to also write a test confirming that the site doesn't blow up with an internal server error when that file is missing.  With-finalizing in `parse_file` looks good.

2024-06-26 17:03 UTC, bufordrat commented
These changes were incorporated into the code by way of PR #766.  Thank you @bluairis for all your work on this.

2024-06-26 17:04 UTC, bufordrat commented
Closing the issue...

2024-06-26 17:04 UTC, closed without merging